services:
  - type: web
    name: voice-mentor-server
    env: python
    region: oregon  # Choose the region closest to you
    plan: free  # Or choose another plan: starter, standard, pro
    
    # Build settings
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
      python -m pip install --upgrade pip
      mkdir -p uploads
      
    # Start command
    startCommand: gunicorn app.server:app --bind 0.0.0.0:$PORT
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: FLASK_APP
        value: app.server
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        sync: false  # Do not synchronize with Git
      - key: OPENAI_API_KEY
        sync: false  # Do not synchronize with Git
        
    # Automatic deployment settings
    autoDeploy: true
    branch: main  # Branch for automatic deployment
    
    # Application health settings
    healthCheckPath: /health
    healthCheckTimeout: 30
    
    # Scaling settings
    scaling:
      minInstances: 1
      maxInstances: 1
      
    # Disk settings
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 